# Generated by Django 6.1 on 2026-08-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MikrotikDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('api_username', models.CharField(max_length=50)),
                ('api_password', models.CharField(max_length=50)),
                ('api_port', models.CharField(max_length=50)),
            ],
        ),
    ]
