# Generated by Django 6.1 on 2026-08-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikdevice',
            name='api_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
