# Generated by Django 6.1 on 2026-08-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_manager', '0002_alter_mikrotikdevice_api_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikdevice',
            name='api_port_8700',
            field=models.CharField(blank=True, default='8700', max_length=50, null=True),
        ),
    ]
