# Generated by Django 6.1 on 2026-08-12 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_manager', '0003_mikrotikdevice_api_port_8700'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikdevice',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mikrotikdevice',
            name='api_password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mikrotikdevice',
            name='api_port',
            field=models.IntegerField(default=8728),
        ),
        migrations.AlterField(
            model_name='mikrotikdevice',
            name='api_port_8700',
            field=models.IntegerField(default=8700),
        ),
        migrations.AlterField(
            model_name='mikrotikdevice',
            name='api_username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mikrotikdevice',
            name='device_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
