# Generated by Django 6.1 on 2026-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_manager', '0005_napbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikdevice',
            name='health_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mikrotikdevice',
            name='health_status',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Moderate', 'Moderate'), ('Poor', 'Poor'), ('Outage', 'Outage')], default='Excellent', max_length=20),
        ),
    ]
