# Generated by Django 5.2.17 on 2026-08-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_manager', '0006_mikrotikdevice_health_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikdevice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='napbox',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
