# Generated by Django 6.1 on 2026-08-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_manager', '0007_alter_mikrotikdevice_id_alter_napbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikdevice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='napbox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
