# Generated by Django 6.1 on 2026-08-11 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('support', 'Support'), ('billing', 'Billing')], default='admin', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=64)),
                ('plan_name', models.CharField(max_length=50)),
                ('speed_up', models.IntegerField(blank=True, null=True)),
                ('speed_down', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_30', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_15', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('validity_days', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField()),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('pull out', 'Pull Out'), ('expired', 'Expired'), ('past_due', 'Past Due')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('adjusted_by_router', models.CharField(blank=True, max_length=100, null=True)),
                ('adjusted_by_referral', models.CharField(blank=True, max_length=250, null=True)),
                ('last_expiry_sms_sent', models.DateTimeField(blank=True, null=True)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=32, null=True)),
                ('agent', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_received', models.CharField(max_length=250)),
                ('last_sms_due', models.DateTimeField(blank=True, null=True)),
                ('connection', models.CharField(max_length=20)),
                ('created_form_by', models.CharField(max_length=250)),
                ('cignalplay_no', models.CharField(blank=True, max_length=64, null=True)),
                ('cignalplay_date', models.DateField(blank=True, null=True)),
                ('cignalplay_adjustedby', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='billing.accounttype')),
                ('mikrotik_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='network_manager.mikrotikdevice')),
                ('service_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='billing.serviceplan')),
            ],
        ),
    ]
