# Generated by Django 6.1 on 2026-08-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='customer',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
