# Generated by Django 6.1 on 2026-08-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_delete_admin_alter_customer_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pppoe_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pppoe_profile',
            field=models.CharField(blank=True, default='default', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_received',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
