# Generated by Django 6.0.5 on 2026-08-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payment'),
        ('billing', '0009_customer_expires_at'),
    ]

    operations = [
    ]
