# Generated by Django 6.1 on 2026-08-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_customer_adjusted_by_referral_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePlan',
        ),
    ]
