# Generated by Django 6.1 on 2026-08-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_customer_adjusted_by_referral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('record_id', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('changed_by', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
