# Generated by Django 6.1 on 2026-08-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_delete_serviceplan'),
        ('billing', '0012_systemlog'),
    ]

    operations = [
    ]
