# Generated by Django 6.1 on 2026-08-13 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_customermachistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('days', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_expiry', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('adjusted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebates', to='billing.customer')),
            ],
        ),
    ]
