# Generated by Django 6.1 on 2026-08-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sync_status',
            field=models.CharField(choices=[('Synced', 'Synced'), ('Failed', 'Failed')], default='Synced', max_length=20),
        ),
    ]
