# Generated by Django 6.1 on 2026-08-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_barangay_health_reason_barangay_health_status_and_more'),
        ('billing', '0021_employeeprofile'),
    ]

    operations = [
    ]
