# Generated by Django 6.1 on 2026-08-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_alter_customer_health_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='health_status',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Low', 'Low'), ('Poor', 'Poor'), ('Unstable', 'Unstable'), ('Stable', 'Stable'), ('Good', 'Good'), ('Strong', 'Strong'), ('Excellent', 'Excellent'), ('Outage', 'Outage')], default='Good', max_length=20),
        ),
    ]
