# Generated by Django 5.2.17 on 2026-08-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_customer_portal_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
