# Generated by Django 5.2.17 on 2026-08-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_customer_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='target_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
