# Generated by Django 6.1 on 2026-09-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_customer_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('Website', 'Website'), ('Game', 'Game')], default='Website', max_length=50)),
                ('target', models.CharField(help_text='URL or IP Address to ping', max_length=255)),
                ('status', models.CharField(choices=[('Up', 'Up'), ('Degraded', 'Degraded'), ('Down', 'Down')], default='Up', max_length=20)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
