# Generated by Django 6.1.1 on 2026-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0037_messagetemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("pending", "Pending"),
                    ("suspended", "Suspended"),
                    ("pull out", "Pull Out"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="type",
            field=models.CharField(
                choices=[("SMS", "SMS"), ("EMAIL", "Email"), ("TEXT", "Text Template")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
