# Generated by Django on 2026-09-15 for Customer installation status decoupling

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0041_cignalplay_account_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="installation_status",
            field=models.CharField(
                choices=[("installed", "Installed"), ("pending", "Pending Installation")],
                db_index=True,
                default="installed",
                help_text="Physical installation status of the subscriber line.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="installed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when physical installation was completed.",
                null=True,
            ),
        ),
    ]
