# Generated by Django for Cignal Subscription Unification (Play No & Box No)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0042_customer_installation_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cignalplay",
            name="addon_type",
        ),
        migrations.RenameField(
            model_name="cignalplay",
            old_name="account_number",
            new_name="cignal_play_no",
        ),
        migrations.AddField(
            model_name="cignalplay",
            name="cignal_box_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
