# Generated by Django 5.2.17 on 2026-09-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0043_cignal_subscription_unification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cignalplay',
            name='hardware_payment_type',
            field=models.CharField(choices=[('cashout', 'Cashout ₱3k'), ('installment', 'Installment ₱250/mo'), ('none', 'App Only / No Box')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='cignalplay',
            name='installments_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cignalplay',
            name='monthly_load_plan',
            field=models.CharField(blank=True, choices=[('149', '42 Channels (₱149)'), ('399', '62 Channels (₱399)')], default='149', max_length=20, null=True),
        ),
    ]
