# Generated by Django 5.2.17 on 2026-09-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_cignalplay_cancellation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('can_access_billing', models.BooleanField(default=False)),
                ('can_access_network_ops', models.BooleanField(default=False)),
                ('can_access_cignal_play', models.BooleanField(default=False)),
                ('can_access_dispatch', models.BooleanField(default=False)),
                ('can_access_administration', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='role',
            field=models.CharField(default='Agent', max_length=50),
        ),
    ]
