# Generated by Django 5.2.17 on 2026-09-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0046_staffrole_alter_systemadmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agent_lock_until',
            field=models.DateTimeField(blank=True, help_text='Until this date, the customer cannot use staggered payments.', null=True),
        ),
    ]
