# Generated by Django 5.2.17 on 2026-09-17 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0047_customer_agent_lock_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agent_lock_until',
            field=models.DateTimeField(blank=True, help_text='Calculated 60 days from Stage 5 Admin Approval. Until this date, the customer cannot use staggered payments.', null=True),
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMABLE', 'Claimable'), ('PAID', 'Paid'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.agent')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customer')),
            ],
        ),
    ]
