# Generated by Django 5.2.17 on 2026-09-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0048_alter_customer_agent_lock_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontransaction',
            name='is_test_data',
            field=models.BooleanField(default=False, help_text='Flags historical/test records to exclude from financial reports'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_test_data',
            field=models.BooleanField(default=False, help_text='Flags test accounts to safely ignore without hard-deleting'),
        ),
        migrations.AddField(
            model_name='rebate',
            name='is_test_data',
            field=models.BooleanField(default=False, help_text='Flags test payments to exclude from revenue'),
        ),
        migrations.AlterUniqueTogether(
            name='commissiontransaction',
            unique_together={('agent', 'customer')},
        ),
    ]
