# Generated by Django 5.2.17 on 2026-09-24 05:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0054_customer_portal_password_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Incentive PHP per qualified customer (default 500.00)', max_digits=10)),
                ('batch_size', models.PositiveIntegerField(default=5, help_text='Number of qualified customers required per payout batch (default 5)')),
                ('lock_days', models.PositiveIntegerField(default=60, help_text='Days staggered lock lasts from installation approval (default 60)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incentive Setting',
                'verbose_name_plural': 'Incentive Settings',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='first_payment_date',
            field=models.DateField(blank=True, help_text='Date of first payment recorded for this customer', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='original_agent',
            field=models.ForeignKey(blank=True, help_text='Permanent original agent who first referred this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originally_referred_customers', to='billing.agent'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='installation_status',
            field=models.CharField(choices=[('installed', 'Installed'), ('pending', 'Pending Installation'), ('closed_not_installed', 'Closed - Not Installed')], db_index=True, default='installed', help_text='Physical installation status of the subscriber line.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('pull out', 'Pull Out'), ('closed_not_installed', 'Closed - Not Installed')], db_index=True, default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentPayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payout amount (e.g. 2,500.00)', max_digits=10)),
                ('customer_count', models.PositiveIntegerField(default=5, help_text='Number of qualified customers in batch (multiples of 5)')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, help_text='e.g. GCash Ref # or Bank Check #', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to='billing.agent')),
                ('customers', models.ManyToManyField(blank=True, related_name='payout_batches', to='billing.customer')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payout_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentQualificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_at', models.DateTimeField(auto_now_add=True)),
                ('qualifying_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('status', models.CharField(choices=[('qualified', 'Qualified'), ('revoked', 'Revoked (Payment Rollback)'), ('paid_out', 'Paid Out')], default='qualified', max_length=20)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_events', to='billing.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_events', to='billing.customer')),
                ('payment', models.ForeignKey(blank=True, help_text='The payment that triggered qualification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifying_events', to='billing.payment')),
                ('payout_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.agentpayoutbatch')),
            ],
            options={
                'ordering': ['-qualified_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAgentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Mandatory reason explaining why the agent assignment was changed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_change_history', to='billing.customer')),
                ('from_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_lost', to='billing.agent')),
                ('to_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_gained', to='billing.agent')),
            ],
            options={
                'verbose_name': 'Customer Agent History',
                'verbose_name_plural': 'Customer Agent Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(help_text='Canonical Philippine mobile: 09XXXXXXXXX', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('preferred_installation_date', models.DateField(blank=True, null=True)),
                ('preferred_payment_method', models.CharField(choices=[('cash', 'Cash on Hand'), ('gcash', 'Direct GCash')], default='cash', max_length=20)),
                ('id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('checklist_completed', 'Checklist Completed'), ('converted', 'Converted to Customer'), ('declined', 'Declined'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=30)),
                ('duplicate_flag', models.BooleanField(db_index=True, default=False, help_text='Flagged if phone or name matches existing customer or prospect')),
                ('duplicate_notes', models.TextField(blank=True, null=True)),
                ('opened_by_staff_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('is_test_data', models.BooleanField(default=False, help_text='Flags test prospect records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Referring agent who submitted the prospect', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='billing.agent')),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='billing.barangay')),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_source', to='billing.customer')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='billing.prospect')),
                ('opened_by_staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_prospects', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='billing.subscriptionplan')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User (staff or agent) who submitted the prospect form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('submit_prospect', 'Can submit prospect referrals'), ('view_own_referrals', 'Can view own referral leads and progress'), ('manage_prospects', 'Can view and manage prospect inbox'), ('run_checklist', 'Can execute onboarding policy checklist'), ('create_customer', 'Can convert prospect and create customer'), ('change_agent', 'Can change customer assigned sales agent'), ('mark_payout_paid', 'Can approve and mark agent payout batches as paid'), ('manage_message_templates', 'Can configure SMS and notification templates')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('in_person', 'In-Person (Walk-In)'), ('phone', 'Phone Call'), ('chat', 'Online Chat')], default='in_person', max_length=20)),
                ('outcome', models.CharField(choices=[('agreed', 'Agreed (Proceed)'), ('declined', 'Declined')], default='agreed', max_length=20)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of policies presented to the applicant')),
                ('item_free_install', models.BooleanField(default=False, help_text='Free installation with standard materials')),
                ('item_specific_plan', models.BooleanField(default=False, help_text='Specific plan speed, monthly fee, and billing cycle agreed')),
                ('item_no_lockin', models.BooleanField(default=False, help_text='No 24-month lock-in period')),
                ('item_staggered_lock', models.BooleanField(default=False, help_text='60-day initial lock on staggered/partial payments')),
                ('item_same_day_repair', models.BooleanField(default=False, help_text='Same-day repair SLA commitment for reports before 2 PM')),
                ('item_rebates_24h', models.BooleanField(default=False, help_text='Automated billing rebates for continuous outages exceeding 24 hours')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_checklists', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_confirmations', to='billing.customer')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_confirmations', to='billing.prospect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
