# Generated by Django on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0055_incentivesetting_customer_first_payment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistconfirmation",
            name="applicant_name",
            field=models.CharField(
                blank=True,
                help_text="Applicant name (for walk-in declines without prospect)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checklistconfirmation",
            name="applicant_phone",
            field=models.CharField(
                blank=True,
                help_text="Applicant phone (for walk-in declines without prospect)",
                max_length=20,
                null=True,
            ),
        ),
    ]
