# Generated by Django 5.2.17 on 2026-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0058_phase3_2_guards_and_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='adjusted_by_referral',
        ),
        migrations.AlterField(
            model_name='customer',
            name='sync_status',
            field=models.CharField(choices=[('Synced', 'Synced'), ('Failed', 'Failed'), ('Blocked', 'Blocked')], default='Synced', max_length=20),
        ),
    ]
