# Generated by Django 5.2.17 on 2026-09-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0059_remove_customer_adjusted_by_referral_and_more'),
        ('billing', '0060_customer_expires_at_index'),
    ]

    operations = [
    ]
