# Generated by Django 5.2.17 on 2026-09-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Captures a schema change that was applied to production out-of-band.

    The `portal_password_plaintext` column already exists in the production
    database (added by hand), but was never committed as a migration. Without
    this file, any freshly built database -- CI, a new developer machine, or a
    test run without --keepdb -- would lack the column and every customer
    portal password save would fail with ProgrammingError.

    Production has therefore had this migration recorded with `--fake` so the
    schema is not altered there; fresh databases get the column for real.
    """

    dependencies = [
        ("billing", "0062_systemadmin_password_plaintext"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="portal_password_plaintext",
            field=models.CharField(
                blank=True,
                help_text="Staff-visible plaintext portal password (for display only, not used for auth)",
                max_length=50,
                null=True,
            ),
        ),
    ]
