# Generated by Django 5.2.17 on 2026-10-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0067_customer_sync_status_unverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='legacy_id',
            field=models.CharField(blank=True, db_index=True, help_text='Payment id from the legacy system. Makes re-import idempotent.', max_length=64, null=True, unique=True),
        ),
    ]
