# Generated by Django 5.2.17 on 2026-10-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0068_payment_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='router_profile',
            field=models.CharField(blank=True, default='', help_text='MikroTik /ppp/profile name. Blank = use the plan name.', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='speed_mbps',
            field=models.IntegerField(blank=True, help_text='Download speed in Mbps. Used to spot duplicate-priced plans.', null=True),
        ),
    ]
