# Generated by Django 5.2.17 on 2026-10-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0071_planmapping_importhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
