# Generated by Django 5.2.17 on 2026-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0072_alter_importhistory_id_alter_planmapping_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='legacy_reimported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
