# Generated by Django 5.2.17 on 2026-10-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0073_customer_legacy_reimported'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermachistory',
            name='replaced_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customermachistory',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customermachistory',
            name='source_ticket',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
