"""
Django settings for gametech_core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import environ
import os

env = environ.Env(DEBUG=(bool, False))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECRET_KEY: Must be set via environment variable in production.
# Generate one with: python -c "from django.core.management.utils import get_random_secret_key as g; print(g())"
SECRET_KEY = env("SECRET_KEY", default="django-insecure-DEV-ONLY-change-me-in-production-9x!k2m")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])
CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=["http://143.198.207.144", "https://143.198.207.144"],
)

# HTTPS / SSL Security Settings (environment-driven, default False until domain/SSL active)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)

# Session idle timeout. Was hardcoded to 300s (5 minutes), which logged staff out
# mid-task -- a CSR filling the onboarding checklist or keying a long payment
# reference would lose the form and be bounced to /login/. Default is one working
# day; the timer still slides on every request, so it is an IDLE timeout, not a
# total session limit. Override with SESSION_COOKIE_AGE in .env.
SESSION_COOKIE_AGE = env.int("SESSION_COOKIE_AGE", default=28800)  # 8 hours
SESSION_SAVE_EVERY_REQUEST = True  # Reset idle timer on each request

# Security headers (applied by SecurityMiddleware)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CSP_DEFAULT_SRC = "'self'"
SECURE_CSP_SCRIPT_SRC = "'self'"
SECURE_CSP_STYLE_SRC = "'self' 'unsafe-inline'"
SECURE_CSP_IMG_SRC = "'self' data:"
SECURE_CSP_FONT_SRC = "'self'"
SECURE_CSP_CONNECT_SRC = "'self'"
SECURE_CSP_FRAME_ANCESTORS = "'none'"
SECURE_CSP_BASE_URI = "'self'"
SECURE_CSP_FORM_ACTION = "'self'"

# Semaphore SMS Configuration (environment-driven)
SEMAPHORE_API_KEY = env("SEMAPHORE_API_KEY", default="")
SEMAPHORE_SENDER_NAME = env("SEMAPHORE_SENDER_NAME", default="SEMAPHORE")

# Trust the Nginx Reverse Proxy Headers
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "http")

# Router Mode: 'dry_run' | 'read_only' | 'live'
# dry_run: Stubs all RouterOS calls via in-memory mock pool (default in tests)
# read_only: Allows real router socket reads (live status, uptime), blocks all writes (default on droplet)
# live: Full read & write to real hardware (set only by administrator at cutover)
import sys
_is_testing = "test" in sys.argv or any("pytest" in str(arg) for arg in sys.argv)
if _is_testing:
    ROUTER_MODE = "dry_run"
    ROUTER_DRY_RUN = True
else:
    ROUTER_MODE = env.str("ROUTER_MODE", default="live").lower().strip()
    if ROUTER_MODE not in ("dry_run", "read_only", "live"):
        ROUTER_MODE = "live"
    # Backward-compatibility alias
    ROUTER_DRY_RUN = (ROUTER_MODE == "dry_run")

# Agent Incentive Engine Kill-Switch (Default: False)
INCENTIVES_ENABLED = env.bool("INCENTIVES_ENABLED", default=False)

# Application definition

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "billing",
    "network_manager",
    "customer_portal",
    "dispatch",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "billing.middleware.LoginRateLimitMiddleware",
    "billing.middleware.APIRateLimitMiddleware",
    "billing.middleware.ThreadLocalUserMiddleware",
    "billing.middleware.ActiveUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "gametech_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": False,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                ("django.template.loaders.cached.Loader", [
                    "django.template.loaders.filesystem.Loader",
                    "django.template.loaders.app_directories.Loader",
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = "gametech_core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR}/db.sqlite3")
}
DATABASES["default"]["CONN_MAX_AGE"] = 60

# Celery Configuration
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# Shared secret for POST /billing/api/bridge/heartbeat/. The droplet host cron
# (scripts/bridge_heartbeat.sh) sends the office Mini PC's real Tailscale state.
# Deliberately defaults to EMPTY so an unconfigured deploy fails closed instead
# of letting anyone on the internet blind the monitoring system.
BRIDGE_HEARTBEAT_TOKEN = env("BRIDGE_HEARTBEAT_TOKEN", default="")


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 10,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "billing.validators.GametechPasswordPolicyValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise compression & caching
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
WHITENOISE_MAX_AGE = 31536000  # 1 year for immutable static files

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
# Forced reload to detect new templates folder

# Authentication Redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"

# Caching
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/1"),
    }
}

# Celery Beat Schedule
from celery.schedules import crontab

# Celery Beat Schedule
#
# SAFETY RULE: nothing on this schedule may WRITE to a router unattended.
# Provisioning, suspension and reconnection are deliberate human actions made
# from the Sync Manager, where the diff is visible first. Two jobs used to run
# here (auto-suspend-hourly and auto-reconcile-routers-30min) and both wrote to
# live routers on a timer -- which meant a config change or a bad import could
# disconnect or re-provision the whole customer base with nobody watching.
# Both are now opt-in commands and are run by hand.
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "auto-sms-daily": {
        "task": "billing.tasks.auto_sms_task",
        "schedule": crontab(hour="9", minute="0"),  # Run daily at 9:00 AM
    },
    "auto-sync-failed-5min": {
        "task": "billing.tasks.auto_sync_failed_task",
        "schedule": crontab(minute="*/5"),  # Run every 5 minutes
    },
    "fetch-live-monitoring-10sec": {
        "task": "billing.tasks.fetch_live_monitoring_data_task",
        "schedule": 10.0,  # Run every 10 seconds
    },
    "auto-cleanup-logs-weekly": {
        "task": "billing.tasks.auto_cleanup_system_logs_task",
        "schedule": crontab(hour="3", minute="0", day_of_week="sunday"),  # Run weekly at 3:00 AM Sunday
    },
    "cignal-expiry-notify-daily": {
        "task": "billing.tasks.cignal_expiry_notification_task",
        "schedule": crontab(hour="8", minute="0"),  # Run daily at 8:00 AM — alerts staff before workday
    },
    # BILLING-ONLY expiry sweep. `auto_suspend` stays unscheduled on purpose
    # (nothing writes to a router unattended), which left nobody noticing that a
    # subscriber had gone past due -- they simply stayed `active` and online.
    # This closes that gap without touching a router: it auto-renews from advance
    # payment and otherwise raises one Notification for staff to action.
    "expiry-sweep-nightly": {
        "task": "billing.tasks.expiry_sweep_task",
        "schedule": crontab(hour="7", minute="15"),  # 7:15 AM, before the workday
    },
    "auto-backup-hourly": {
        "task": "billing.tasks.automated_backup_task",
        "schedule": crontab(minute="0"),  # Run at the top of every hour
        "kwargs": {"backup_type": "hourly"},
    },
    "auto-backup-daily": {
        "task": "billing.tasks.automated_backup_task",
        "schedule": crontab(hour="2", minute="0"),  # Run daily at 2:00 AM
        "kwargs": {"backup_type": "daily"},
    },
}
