# Generated by Django 6.1 on 2026-09-02 02:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0034_customer_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('STATUS', 'STATUS'), ('TYPE', 'TYPE'), ('CHAT_TYPE', 'CHAT_TYPE')], max_length=20)),
                ('module', models.CharField(choices=[('DISPATCH', 'DISPATCH'), ('MONITORING', 'MONITORING')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(default='gray', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('hardcoded', models.BooleanField(default=False)),
                ('dispatch_equivalent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equivalent_of', to='dispatch.configoption')),
            ],
            options={
                'unique_together': {('list_type', 'module', 'label')},
            },
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('client_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=50)),
                ('concern', models.TextField()),
                ('sales_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_accomplish', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('done_duration', models.IntegerField(blank=True, null=True)),
                ('source_tab', models.CharField(choices=[('INTERNET_INSTALL', 'INTERNET_INSTALL'), ('CIGNAL_PLAY', 'CIGNAL_PLAY'), ('CLIENT_CONCERNS', 'CLIENT_CONCERNS')], max_length=30)),
                ('ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_type_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dispatch_chat_types', to='dispatch.configoption')),
                ('csr', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='handled_dispatches', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='billing.customer')),
                ('status_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dispatch_statuses', to='dispatch.configoption')),
                ('type_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dispatch_types', to='dispatch.configoption')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_type', models.CharField(choices=[('INTERNET_INSTALL', 'INTERNET_INSTALL'), ('CIGNAL_PLAY', 'CIGNAL_PLAY'), ('CLIENT_CONCERNS', 'CLIENT_CONCERNS')], max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('client_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=50)),
                ('concern', models.TextField()),
                ('sales_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_accomplish', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('done_duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_type_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='monitoring_chat_types', to='dispatch.configoption')),
                ('csr', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='handled_monitoring_records', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_records', to='billing.customer')),
                ('dispatch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_record', to='dispatch.dispatchrecord')),
                ('status_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='monitoring_statuses', to='dispatch.configoption')),
                ('type_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='monitoring_types', to='dispatch.configoption')),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay_city', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('job_order', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('nap_port', models.CharField(blank=True, max_length=100, null=True)),
                ('cable_length', models.CharField(blank=True, max_length=100, null=True)),
                ('nap_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('pole_number', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_package', models.CharField(blank=True, max_length=100, null=True)),
                ('ont_modem_sn', models.CharField(blank=True, max_length=100, null=True)),
                ('signal_level', models.CharField(blank=True, max_length=100, null=True)),
                ('facility', models.CharField(blank=True, max_length=100, null=True)),
                ('house_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('technician_remarks', models.TextField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_detail', to='dispatch.monitoringrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('target_per_day', models.IntegerField(default=0)),
                ('target_per_month', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='dispatch.team')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='monitoringrecord',
            name='teams',
            field=models.ManyToManyField(related_name='monitoring_records', to='dispatch.technician'),
        ),
        migrations.AddField(
            model_name='dispatchrecord',
            name='teams',
            field=models.ManyToManyField(related_name='dispatches', to='dispatch.technician'),
        ),
    ]
