# Generated by Django 6.1 on 2026-09-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='sla_rebates_given',
            field=models.IntegerField(default=0, help_text='Number of 24h SLA rebate days automatically given'),
        ),
    ]
