# Generated by Django 5.2.17 on 2026-09-16 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0044_cignalplay_hardware_payment_type_and_more'),
        ('dispatch', '0003_dispatchrecord_sla_rebates_given'),
        ('network_manager', '0008_alter_mikrotikdevice_id_alter_napbox_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='mikrotik_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='network_manager.mikrotikdevice'),
        ),
        migrations.CreateModel(
            name='JobTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('ticket_type', models.CharField(choices=[('INSTALLATION', 'New Installation'), ('REPAIR', 'Repair / Client Concern'), ('CIGNAL', 'Cignal Play / Box'), ('MIGRATION', 'Plan / Line Migration'), ('RELOCATION', 'Relocation / Transfer'), ('PULL_OUT', 'Pull Out / Disconnection')], default='INSTALLATION', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('ASSIGNED', 'Assigned / Scheduled'), ('IN_PROGRESS', 'In Progress / On Site'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('source_tab', models.CharField(choices=[('INTERNET_INSTALL', 'INTERNET_INSTALL'), ('CIGNAL_PLAY', 'CIGNAL_PLAY'), ('CLIENT_CONCERNS', 'CLIENT_CONCERNS')], default='INTERNET_INSTALL', max_length=30)),
                ('client_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_package', models.CharField(blank=True, max_length=100, null=True)),
                ('concern', models.TextField(blank=True, null=True)),
                ('chat_type', models.CharField(blank=True, default='Walk-In / Direct', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nap_port', models.CharField(blank=True, max_length=100, null=True)),
                ('cable_length', models.CharField(blank=True, max_length=100, null=True)),
                ('nap_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('pole_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ont_modem_sn', models.CharField(blank=True, max_length=100, null=True)),
                ('signal_level', models.CharField(blank=True, max_length=100, null=True)),
                ('facility', models.CharField(blank=True, max_length=100, null=True)),
                ('house_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('technician_remarks', models.TextField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_accomplish', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('done_duration', models.IntegerField(blank=True, null=True)),
                ('sla_rebates_given', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='billing.customer')),
                ('mikrotik_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_tickets', to='network_manager.mikrotikdevice')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='dispatch.team')),
                ('technicians', models.ManyToManyField(blank=True, related_name='job_tickets', to='dispatch.technician')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
