# Generated by Django 5.2.17 on 2026-09-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_dispatchrecord_mikrotik_device_jobticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrecord',
            name='facebook_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='facebook_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitoringrecord',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='monitoringrecord',
            name='facebook_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
