# Generated by Django 5.2.17 on 2026-09-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_dispatchrecord_alternate_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='payment_collected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='qa_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='qa_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
