# Generated by Django 5.2.17 on 2026-09-17 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_jobticket_payment_collected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Checked if the technician is on duty and available for assignment'),
        ),
        migrations.AlterField(
            model_name='jobticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('ASSIGNED', 'Assigned / Scheduled'), ('IN_PROGRESS', 'In Progress / On Site'), ('COMPLETED', 'Completed (Awaiting QA)'), ('QA_PASSED', 'QA Passed (Awaiting Approval)'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='JobTicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='dispatch.jobticket')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
