# Generated by Django 5.2.17 on 2026-09-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_sales_agent_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], db_index=True, default='CASH', max_length=30, null=True),
        ),
    ]
