# Generated by Django 5.2.17 on 2026-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_jobticket_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('no_contact', 'Client Unreachable (No Contact)'), ('change_of_mind', 'Change of Mind'), ('undecided', 'Undecided'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='contact_attempt_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times technician tried to reach client (max 3)'),
        ),
    ]
