# Generated by Django 5.2.17 on 2026-09-24 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_jobticket_cancellation_reason_jobticket_contact_attempt_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobticket',
            options={'ordering': ['-created_at'], 'permissions': [('assign_technicians', 'Can assign technicians to job tickets'), ('technician_job_actions', 'Can execute field technician mobile job actions'), ('correct_timers', 'Can adjust technician arrived/done timers'), ('dispatch_qa', 'Can review field reports and QA job tickets'), ('admin_approve', 'Can grant final admin sign-off on jobs'), ('view_bounce_summary', 'Can view bounce-back summary and pattern metrics')]},
        ),
        migrations.AddField(
            model_name='jobticket',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin signed off on job completion', null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='When field technician clicked Arrived on site', null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='bounce_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this ticket has been bounced back'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='client_agent_informed',
            field=models.BooleanField(default=False, help_text="Checked by dispatch when informing client's agent of unreachable/cancellation"),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='client_called_by_qa',
            field=models.BooleanField(default=False, help_text='Checked if QA dispatcher called client for verification'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='close_reason',
            field=models.CharField(blank=True, help_text='Undecided, Change of mind, Unreachable, Other', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='close_reason_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='When field technician clicked Done on site', null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='qa_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_reviewed_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='repeated_bounce_alert',
            field=models.BooleanField(default=False, help_text='Flagged when ticket bounces 2 or more times'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='same_person_flag',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged if same actor handled multiple stages'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='same_person_stages',
            field=models.JSONField(blank=True, default=list, help_text='List of stage names handled by the same person'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='technician_report',
            field=models.TextField(blank=True, help_text='Work done report entered by technician', null=True),
        ),
        migrations.AlterField(
            model_name='jobticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('ASSIGNED', 'Assigned / Scheduled'), ('IN_PROGRESS', 'In Progress / On Site'), ('COMPLETED', 'Completed (Awaiting QA)'), ('QA_PASSED', 'QA Passed (Awaiting Approval)'), ('APPROVED', 'Admin Approved / Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobticket',
            name='ticket_type',
            field=models.CharField(choices=[('INSTALLATION', 'New Installation'), ('REPAIR', 'Repair / Client Concern'), ('CIGNAL', 'Cignal Play / Box'), ('MIGRATION', 'Plan / Line Migration'), ('RELOCATION', 'Relocation / Transfer'), ('PULL_OUT', 'Pull Out / Disconnection'), ('SITE_VISIT', 'Site Visit')], default='INSTALLATION', max_length=30),
        ),
        migrations.CreateModel(
            name='CallAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1st, 2nd, 3rd call attempt')),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('unanswered', 'Unanswered'), ('rejected', 'Rejected / Call Declined'), ('busy', 'Line Busy'), ('client_declined', 'Client Declined / Cancelled'), ('other', 'Other')], default='unanswered', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_attempts', to='dispatch.technician')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='dispatch.jobticket')),
            ],
            options={
                'ordering': ['attempt_number', 'attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='TicketBounceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(max_length=50)),
                ('to_stage', models.CharField(max_length=50)),
                ('bounce_type', models.CharField(choices=[('revisit', 'Revisit with new timer'), ('correct_report', 'Correct the report')], default='correct_report', max_length=50)),
                ('reason', models.TextField(help_text='Mandatory reason for bouncing ticket back')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bounced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounced_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounces', to='dispatch.jobticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
