# Generated by Django 5.2.17 on 2026-09-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_dispatchrecord_monitoring_link_and_job_detail'),
        ('dispatch', '0013_jobticket_is_flagged_and_more'),
    ]

    operations = [
    ]
