# Generated by Django 5.2.17 on 2026-09-29 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0014_merge_20260929_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringrecord',
            name='dispatch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_record', to='dispatch.dispatchrecord'),
        ),
    ]
