# Generated by Django 5.2.17 on 2026-10-10 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0016_alter_technician_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='ont_modem_mac',
            field=models.CharField(blank=True, help_text='Home modem MAC captured by the technician at final submission (AA:BB:CC:DD:EE:FF)', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='configoption',
            name='list_type',
            field=models.CharField(choices=[('STATUS', 'STATUS'), ('TYPE', 'TYPE'), ('CHAT_TYPE', 'CHAT_TYPE'), ('REPLACEMENT_REASON', 'REPLACEMENT_REASON')], max_length=20),
        ),
        migrations.CreateModel(
            name='TicketTechnicianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('replacement_note', models.TextField(blank=True, help_text="Required when the replacement reason is 'Other'.", null=True)),
                ('job_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_assignments', to='dispatch.jobticket')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces_assignments', to='dispatch.technician')),
                ('replaced_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_replacements_made', to=settings.AUTH_USER_MODEL)),
                ('replacement_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_reasons', to='dispatch.configoption')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignments', to='dispatch.technician')),
            ],
            options={
                'ordering': ['job_ticket_id', 'sequence'],
                'unique_together': {('job_ticket', 'technician', 'sequence')},
            },
        ),
    ]
